name: SSH deploy

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get public IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Add IP to whitelist
        id: addip
        run: |
          curl -H "Content-Type: application/json" -H "Authorization: Bearer ${{ secrets.ADM_TOOLS_API_TOKEN }}" --request POST --data '{"account_id": "${{ secrets.ADM_TOOLS_ACCOUNT_ID }}", "ip": "${{ steps.ip.outputs.ipv4 }}"}' https://adm.tools/action/hosting/account/ssh/ip/send/

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy wp-content to server
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          remote_host: ${{ secrets.SERVER_HOST}}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.REMOTE_KEY }}
          remote_path: ${{ secrets.SERVER_PATH }}

      - name: Remove IP from whitelist
        id: removeip
        run: |
          curl -H "Content-Type: application/json" -H "Authorization: Bearer ${{ secrets.ADM_TOOLS_API_TOKEN }}" --request POST --data '{"account_id": "${{ secrets.ADM_TOOLS_ACCOUNT_ID }}", "ip": "${{ steps.ip.outputs.ipv4 }}"}' https://adm.tools/action/hosting/account/ssh/ip/delete_by_ip/